# coins to track
coins:

# repos to push data to (multiple repos are allowed)
repos:

# interval is the frequency of data being gathered and stored.
# Available intervals are: "hourly", and "daily"
interval: "hourly"
