# coins to track
coins:
  - etherium
  - bitcoin
  - ripple

# repos to push data to (multiple repos are allowed)
repos:
  # - repo1
  # - repo2

# if the app is in "monitor" mode, define the times when the data will be gathered and pushed (24 HR clock)
# it will choose the first successful time, others are fallbacks
times:
  - 8
  - 9
  - 15
